### ISSUE TITLE
Links to summon is broken in README

### ISSUE THREAD

**Issue by dustinmm80** [lookout/summon-cerberus#7]
Summon is now hosted at
- https://cyberark.github.io/summon (docs)
- https://github.com/cyberark/summon (repo)

**Comment by burdzwastaken** [comment]
@dustinmm80 this will be fixed in: https://github.com/lookout/summon-cerberus/pull/8/files

**Comment by dustinmm80** [comment]
Thanks very much!

**Comment by burdzwastaken** [comment]
@rohitasva can you close this issue?
